### ISSUE TITLE
Interferes with transpilation

### ISSUE THREAD

**Issue by letmaik** [aMarCruz/jsccify#1]
I found a problem trying to put a debug logging function in a separate module using ES6 modules:

Source "main.js":
```js
//#if _DEBUG
//#set _LOG 'debugout'
import {$_LOG} from './mymodule'
//#else
//#set _LOG '//'
//#endif

$_LOG('Oops!')
```

Source "mymodule.js":
```js
/*#if _DEBUG
export function debugout (s) {
  console.log(s)
}
//#elif 0 // */
export const $_LOG = null
//#endif
```

In all other submodules (imported from main.js) I could then shorten the boilerplate to the following since _LOG has already been set through main.js. I think there's no easy solution to get rid of the if condition since it is part of the import clause:
```js
//#if _DEBUG
import {$_LOG} from './mymodule'
//#endif
```

After running browserify without jsccify:
```js
mymodule.$_LOG('Oops!');
```
After running  browserify with jsccify and _DEBUG = 0:
```js
mymodule.//('Oops!');
```
This is the problem. It seems to apply jscc a bit too late.

After running  browserify with jsccify and _DEBUG = 1:
```js
mymodule.debugout('Oops!');
```
But now it is complaining that debugout is not defined in the other module which probably means that some processing order is not right.

Note that the same is working with the rollup plugin.

I use `-t jsccify -p tsify` as browserify options. The `tsify` is for TypeScript transpilation but I guess the same would happen with any kind of transpilation.

**Comment by aMarCruz** [comment]
@letmaik please test changing "mymodule.js" to this:

``` js
//#if _DEBUG
export function debugout (s) {
  console.log(s)
}
//#endif
```

if it does not work, then define _LOG as global too

``` js
  ...
  jscc({ values: { _LOG: '//' } })
```

I'm not in my dev machine right now, I'll test it tomorrow.
